import { Component, OnInit } from '@angular/core';
import { jobDescription as jobDescription } from 'src/app/models/job-description';

@Component({
  selector: 'app-job-descriptions',
  templateUrl: './job-descriptions.component.html',
  styleUrls: ['./job-descriptions.component.scss']
})
export class JobDescriptionsComponent implements OnInit {
  datas: jobDescription[] = [];

  ngOnInit(): void {
    this.datas = [
      new jobDescription('2020-09-01', '2022-06-01', 'TDCX', 'My main responsibility as an outsourced L&D personnel is to consult on circumstances or desired outcomes presented from a learning point of view. I have lead and onboarded 3 greenfield projects from Automotive, Retail & Electronic industries. I was also given responsibility to oversee a running e-commerce project. Experience within these projects have allowed me to have a full hands-on experience in Planning, Doing, Checking and Acting (PDCA). During the onboarding of new projects, L & D end - to - end process were required starting with developing training roadmap and proposal.This includes day - to - day training agenda and modules development inclusive of process mapping.The job requires close relationship with clients and stakeholders to ensure all departments are aligned.Post - training, L1 - L4(if applicable) Evaluations were provided to relevant stakeholders.Following this, Weekly, Monthly & Quarterly Business Reviews were conducted where training analysis and results were presented to upkeep performances.  Workshop and other refresher training were developed and conducted within each project to promote a continuous learning culture. My task outside the projects is to manage 3 trainers, a Document Control Person for ISO Audits and TNA.Have been recognized for "Never Stop Thinking" award and a Gold Certified Trainer', ['a', 'b', 'c']),
      new jobDescription('2019-02-01', '2020-08-01', 'Ecart Services Malaysia {Lazada Malaysia)', '​As an in-house trainer, my key responsibility is to liaise closely with stakeholders (Operations & QA) to ensure the Customer Satisfaction (CSAT) index is met for both in-house and BPO.  This includes Training Needs Analysis where importance is set for finding out the gap(s) agents faced and finding the corrective solution with collaboration from the QA team. Once a module is developed, a Train-The-Trainer session was conducted with 3 BPO trainers. In charge of training delivery and reporting.  As Lazada is a fast-paced industry, this job highly demands proactivity. I was responsible for campaign training, soft skills workshop, help center articles, announcements, and usage of LMS (Articulate & Docebo). Business Reviews were conducted on a monthly and quarterly basis where challenges and support were shared during BPO presentations. Has a close relationship with the regional team and was an active member of the company. Appointed as their official live show host during major campaigns.', ['a', 'b', 'c']),
      new jobDescription('2018-09-01', '2019-02-01','Ecart Services Malaysia {Lazada Malaysia)', '​As an in-house trainer, my key responsibility is to liaise closely with stakeholders (Operations & QA) to ensure the Customer Satisfaction (CSAT) index is met for both in-house and BPO.  This includes Training Needs Analysis where importance is set for finding out the gap(s) agents faced and finding the corrective solution with collaboration from the QA team. Once a module is developed, a Train-The-Trainer session was conducted with 3 BPO trainers. In charge of training delivery and reporting.  As Lazada is a fast-paced industry, this job highly demands proactivity. I was responsible for campaign training, soft skills workshop, help center articles, announcements, and usage of LMS (Articulate & Docebo). Business Reviews were conducted on a monthly and quarterly basis where challenges and support were shared during BPO presentations. Has a close relationship with the regional team and was an active member of the company. Appointed as their official live show host during major campaigns.', ['a', 'b', 'c']),
      new jobDescription('2018-04-01', '2018-08-01','Ecart Services Malaysia {Lazada Malaysia)', '​As an in-house trainer, my key responsibility is to liaise closely with stakeholders (Operations & QA) to ensure the Customer Satisfaction (CSAT) index is met for both in-house and BPO.  This includes Training Needs Analysis where importance is set for finding out the gap(s) agents faced and finding the corrective solution with collaboration from the QA team. Once a module is developed, a Train-The-Trainer session was conducted with 3 BPO trainers. In charge of training delivery and reporting.  As Lazada is a fast-paced industry, this job highly demands proactivity. I was responsible for campaign training, soft skills workshop, help center articles, announcements, and usage of LMS (Articulate & Docebo). Business Reviews were conducted on a monthly and quarterly basis where challenges and support were shared during BPO presentations. Has a close relationship with the regional team and was an active member of the company. Appointed as their official live show host during major campaigns.', ['a', 'b', 'c']),
      new jobDescription('2014-10-01', '2018-04-01','Ecart Services Malaysia {Lazada Malaysia)', '​As an in-house trainer, my key responsibility is to liaise closely with stakeholders (Operations & QA) to ensure the Customer Satisfaction (CSAT) index is met for both in-house and BPO.  This includes Training Needs Analysis where importance is set for finding out the gap(s) agents faced and finding the corrective solution with collaboration from the QA team. Once a module is developed, a Train-The-Trainer session was conducted with 3 BPO trainers. In charge of training delivery and reporting.  As Lazada is a fast-paced industry, this job highly demands proactivity. I was responsible for campaign training, soft skills workshop, help center articles, announcements, and usage of LMS (Articulate & Docebo). Business Reviews were conducted on a monthly and quarterly basis where challenges and support were shared during BPO presentations. Has a close relationship with the regional team and was an active member of the company. Appointed as their official live show host during major campaigns.', ['a', 'b', 'c']),
  ]}
}